// <auto-generated />
using System;
using Bud.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bud.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bud.Server.Domain.Model.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsGlobalAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LeaderId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.CollaboratorAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("OrganizationId", "AccessedAt");

                    b.ToTable("CollaboratorAccessLogs");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.CollaboratorTeam", b =>
                {
                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CollaboratorId", "TeamId");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("TeamId");

                    b.ToTable("CollaboratorTeams");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MetricCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("MetricId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("MetricId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MetricCheckins");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantitativeType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MissionMetrics");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("Dimension")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("Dimension");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MissionObjectives");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MissionDescriptionPattern")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MissionNamePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MissionTemplates");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplateMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MissionTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MissionTemplateObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantitativeType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionTemplateId");

                    b.HasIndex("MissionTemplateObjectiveId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MissionTemplateMetrics");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplateObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MissionTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("Dimension")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissionTemplateId");

                    b.HasIndex("Dimension");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MissionTemplateObjectives");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientCollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RecipientCollaboratorId", "IsRead", "CreatedAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.ObjectiveDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ObjectiveDimensions");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParentTeamId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Collaborator", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Team", "Team")
                        .WithMany("Collaborators")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leader");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.CollaboratorAccessLog", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.CollaboratorTeam", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Collaborator")
                        .WithMany("CollaboratorTeams")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Team", "Team")
                        .WithMany("CollaboratorTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MetricCheckin", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Metric", "Metric")
                        .WithMany("Checkins")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Metric");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Mission", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collaborator");

                    b.Navigation("Organization");

                    b.Navigation("Team");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Metric", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Mission", "Mission")
                        .WithMany("Metrics")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Objective", "Objective")
                        .WithMany("Metrics")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Objective");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Objective", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Mission", "Mission")
                        .WithMany("Objectives")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.ObjectiveDimension", "ObjectiveDimension")
                        .WithMany()
                        .HasForeignKey("Dimension")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("ObjectiveDimension");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplate", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplateMetric", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.MissionTemplate", "MissionTemplate")
                        .WithMany("Metrics")
                        .HasForeignKey("MissionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.MissionTemplateObjective", "MissionTemplateObjective")
                        .WithMany("Metrics")
                        .HasForeignKey("MissionTemplateObjectiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MissionTemplate");

                    b.Navigation("MissionTemplateObjective");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplateObjective", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.MissionTemplate", "MissionTemplate")
                        .WithMany("Objectives")
                        .HasForeignKey("MissionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.ObjectiveDimension", "ObjectiveDimension")
                        .WithMany()
                        .HasForeignKey("Dimension")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MissionTemplate");

                    b.Navigation("ObjectiveDimension");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Notification", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "RecipientCollaborator")
                        .WithMany()
                        .HasForeignKey("RecipientCollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("RecipientCollaborator");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.ObjectiveDimension", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Organization", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Team", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Collaborator", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bud.Server.Domain.Model.Team", "ParentTeam")
                        .WithMany("SubTeams")
                        .HasForeignKey("ParentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bud.Server.Domain.Model.Workspace", "Workspace")
                        .WithMany("Teams")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");

                    b.Navigation("Organization");

                    b.Navigation("ParentTeam");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Workspace", b =>
                {
                    b.HasOne("Bud.Server.Domain.Model.Organization", "Organization")
                        .WithMany("Workspaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Collaborator", b =>
                {
                    b.Navigation("CollaboratorTeams");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Mission", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Metric", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Objective", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplate", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Objectives");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.MissionTemplateObjective", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Organization", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Team", b =>
                {
                    b.Navigation("CollaboratorTeams");

                    b.Navigation("Collaborators");

                    b.Navigation("SubTeams");
                });

            modelBuilder.Entity("Bud.Server.Domain.Model.Workspace", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
