steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE_URI}
      - --target
      - ${_DOCKER_TARGET}
      - -f
      - backend/${_DOCKERFILE}
      - backend
substitutions:
  _DOCKERFILE: Dockerfile.Production
images:
  - ${_IMAGE_URI}
